server:
  port: 0
  servlet:
    session:
      timeout: 120s

spring:
  application:
    name: ali-ai-helper
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
    include: web

langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen3-max
        api-key: ${AI_DASHSCOPE_API_KEY}
      streaming-chat-model:
        model-name: qwen3-max
        api-key: ${AI_DASHSCOPE_API_KEY}
      embedding-model:
        model-name: text-embedding-v4
        api-key: ${AI_DASHSCOPE_API_KEY}
bigmodel:
  api-key: ${AI_DASHSCOPE_API_KEY}
